# Часть 1.

In [1]:
import numpy as np

## Задание 2

In [5]:
A=np.array([[1, -2],
           [3, 0]])
B=np.array([[4, -1],
           [0, 5]])
print(f'A+B\n{A + B}')
print(f'A*B\n{np.dot(A,B)}')

A+B
[[ 5 -3]
 [ 3  5]]
A*B
[[  4 -11]
 [ 12  -3]]


## Задание 3

In [6]:
A=np.array([[1, 7],
           [3, -6]])
B=np.array([[0, 5],
           [2, -1]])
C=np.array([[2, -4],
           [1, 1]])
print(f'3A-2B+4C=\n{3*A-2*B+4*C}')

3A-2B+4C=
[[ 11  -5]
 [  9 -12]]


## Задание 4

In [7]:
A=np.array([[4, 1],
           [5, -2],
           [2, 3]])
AT=A.T
print(f'AAT=\n{np.dot(A, AT)}')
print(f'ATA=\n{np.dot(AT, A)}')

AAT=
[[17 18 11]
 [18 29  4]
 [11  4 13]]
ATA=
[[45  0]
 [ 0 14]]


# Часть 2.

## Задание 1

In [9]:
A=np.array([[4, 2, 3],
           [0, 5, 1],
           [0, 0, 9]])
print(f'Матрица A=\n{A}')
print(f'Определитель =\n{np.linalg.det(A):.0f}')
B=np.array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])
print(f'Матрица B=\n{B}')
print(f'Определитель =\n{np.linalg.det(B):.0f}')

Матрица A=
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель =
180
Матрица B=
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель =
-0


## Задание 3

In [17]:
A=np.array([[-2, 7, -3],
           [4, -14, 6],
           [-3, 7, 13]])
print(f'Определитель =\n{np.linalg.det(A):.0f}')

Определитель =
0


## Задание 4

In [18]:
A=np.array([[1, 2, 3],
           [1, 1, 1],
           [2, 3, 4]])
print(f'Ранг матрицы: {np.linalg.matrix_rank(A)}')

Ранг матрицы: 2


In [19]:
B=np.array([[0, 0, 2, 1],
           [0, 0, 2, 2],
           [0, 0, 4, 3],
           [2, 3, 5, 6]])
print(f'Ранг матрицы: {np.linalg.matrix_rank(B)}')

Ранг матрицы: 3
